# Generated by Django 4.1.4 on 2022-12-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segundo_app', '0002_endereco_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=100, verbose_name='CEP'),
        ),
    ]
